{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "42324b4b-c033-4b25-9744-72890237fb3a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Collecting torchdiffeq\n",
      "  Downloading torchdiffeq-0.2.5-py3-none-any.whl.metadata (440 bytes)\n",
      "Collecting torchmetrics\n",
      "  Downloading torchmetrics-1.7.0-py3-none-any.whl.metadata (21 kB)\n",
      "Requirement already satisfied: torch>=1.5.0 in c:\\users\\tushar\\appdata\\roaming\\python\\python312\\site-packages (from torchdiffeq) (2.6.0)\n",
      "Requirement already satisfied: scipy>=1.4.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from torchdiffeq) (1.13.1)\n",
      "Requirement already satisfied: numpy>1.20.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from torchmetrics) (1.26.4)\n",
      "Requirement already satisfied: packaging>17.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from torchmetrics) (24.1)\n",
      "Collecting lightning-utilities>=0.8.0 (from torchmetrics)\n",
      "  Downloading lightning_utilities-0.14.2-py3-none-any.whl.metadata (5.6 kB)\n",
      "Requirement already satisfied: setuptools in c:\\programdata\\anaconda3\\lib\\site-packages (from lightning-utilities>=0.8.0->torchmetrics) (75.1.0)\n",
      "Requirement already satisfied: typing_extensions in c:\\programdata\\anaconda3\\lib\\site-packages (from lightning-utilities>=0.8.0->torchmetrics) (4.11.0)\n",
      "Requirement already satisfied: filelock in c:\\programdata\\anaconda3\\lib\\site-packages (from torch>=1.5.0->torchdiffeq) (3.13.1)\n",
      "Requirement already satisfied: networkx in c:\\programdata\\anaconda3\\lib\\site-packages (from torch>=1.5.0->torchdiffeq) (3.3)\n",
      "Requirement already satisfied: jinja2 in c:\\programdata\\anaconda3\\lib\\site-packages (from torch>=1.5.0->torchdiffeq) (3.1.4)\n",
      "Requirement already satisfied: fsspec in c:\\programdata\\anaconda3\\lib\\site-packages (from torch>=1.5.0->torchdiffeq) (2024.6.1)\n",
      "Requirement already satisfied: sympy==1.13.1 in c:\\users\\tushar\\appdata\\roaming\\python\\python312\\site-packages (from torch>=1.5.0->torchdiffeq) (1.13.1)\n",
      "Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from sympy==1.13.1->torch>=1.5.0->torchdiffeq) (1.3.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from jinja2->torch>=1.5.0->torchdiffeq) (2.1.3)\n",
      "Downloading torchdiffeq-0.2.5-py3-none-any.whl (32 kB)\n",
      "Downloading torchmetrics-1.7.0-py3-none-any.whl (960 kB)\n",
      "   ---------------------------------------- 0.0/960.9 kB ? eta -:--:--\n",
      "   --------------------------------------- 960.9/960.9 kB 11.1 MB/s eta 0:00:00\n",
      "Downloading lightning_utilities-0.14.2-py3-none-any.whl (28 kB)\n",
      "Installing collected packages: lightning-utilities, torchmetrics, torchdiffeq\n",
      "Successfully installed lightning-utilities-0.14.2 torchdiffeq-0.2.5 torchmetrics-1.7.0\n"
     ]
    }
   ],
   "source": [
    "!pip install numpy torch nibabel \n",
    "import numpy as np\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torchdiffeq\n",
    "import nibabel as nib\n",
    "from pathlib import Path\n",
    "from torch.utils.data import Dataset, DataLoader"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "22250cd7-e2ff-493a-872a-1ff9d07152d9",
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "cannot unpack non-iterable WindowsPath object",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[3], line 89\u001b[0m\n\u001b[0;32m     87\u001b[0m \u001b[38;5;66;03m# Access Patient-067 data\u001b[39;00m\n\u001b[0;32m     88\u001b[0m patient_067_weeks \u001b[38;5;241m=\u001b[39m dataset\u001b[38;5;241m.\u001b[39mget_patient_weeks(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mPatient-067\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[1;32m---> 89\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mPatient 067 has scans at weeks: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00m[w\u001b[38;5;241m.\u001b[39mname\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mfor\u001b[39;00m\u001b[38;5;250m \u001b[39m_,\u001b[38;5;250m \u001b[39mw\u001b[38;5;250m \u001b[39m\u001b[38;5;129;01min\u001b[39;00m\u001b[38;5;250m \u001b[39mpatient_067_weeks]\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m     91\u001b[0m \u001b[38;5;66;03m# Get specific week data\u001b[39;00m\n\u001b[0;32m     92\u001b[0m sample \u001b[38;5;241m=\u001b[39m dataset[\u001b[38;5;241m0\u001b[39m]\n",
      "\u001b[1;31mTypeError\u001b[0m: cannot unpack non-iterable WindowsPath object"
     ]
    }
   ],
   "source": [
    "import torch\n",
    "from torch.utils.data import Dataset\n",
    "from pathlib import Path\n",
    "import nibabel as nib\n",
    "import numpy as np\n",
    "\n",
    "class LUMIEREDataset(Dataset):\n",
    "    def __init__(self, root_dir, modalities=('CT1', 'T1', 'T2', 'FLAIR'),\n",
    "                 segmentation_type='DeepBraTumIA', norm_params=None):\n",
    "        \"\"\"\n",
    "        Args:\n",
    "            root_dir (Path): Path to LUMIERE dataset directory\n",
    "            modalities (tuple): MRI sequences as per dataset structure\n",
    "            segmentation_type (str): 'DeepBraTumIA' or 'HD-GLIO-AUTO'\n",
    "            norm_params (dict): Normalization values from Table 2\n",
    "        \"\"\"\n",
    "        super().__init__()\n",
    "        self.root_dir = Path(root_dir)\n",
    "        self.modalities = modalities\n",
    "        self.segmentation_type = segmentation_type\n",
    "        self.norm_params = norm_params or {\n",
    "            'CT1': {'mean': 0.94, 'std': 0.17},\n",
    "            'T1': {'mean': 0.71, 'std': 0.21},\n",
    "            'T2': {'mean': 0.70, 'std': 0.26},\n",
    "            'FLAIR': {'mean': 0.60, 'std': 0.21}\n",
    "        }\n",
    "        \n",
    "        # Collect all valid patient-week pairs\n",
    "        self.patient_weeks = []\n",
    "        for patient_dir in self.root_dir.glob('Patient-*'):\n",
    "            if patient_dir.is_dir():\n",
    "                weeks = sorted([w for w in patient_dir.iterdir() if w.name.startswith('week')],\n",
    "                             key=lambda x: self._extract_week_number(x.name))\n",
    "                if weeks:  # Only include patients with at least one week\n",
    "                    self.patient_weeks.extend([(patient_dir, week) for week in weeks])\n",
    "\n",
    "    def __len__(self):\n",
    "        return len(self.patient_weeks)\n",
    "\n",
    "    def __getitem__(self, idx):\n",
    "        patient_dir, week_dir = self.patient_weeks[idx]\n",
    "        \n",
    "        # Load MRI modalities [4, H, W, D]\n",
    "        mri_data = []\n",
    "        for modality in self.modalities:\n",
    "            img_path = week_dir / f\"{modality}.nii.gz\"\n",
    "            data = nib.load(img_path).get_fdata()\n",
    "            normalized = (data - self.norm_params[modality]['mean']) / self.norm_params[modality]['std']\n",
    "            mri_data.append(torch.FloatTensor(normalized))\n",
    "        \n",
    "        # Stack modalities [C, H, W, D]\n",
    "        mri_stack = torch.stack(mri_data)\n",
    "        \n",
    "        # Load segmentation from appropriate subdirectory\n",
    "        seg_path = week_dir / f\"{self.segmentation_type}-segmentation\" / \"segmentation.nii.gz\"\n",
    "        seg_data = nib.load(seg_path).get_fdata()\n",
    "        seg_tensor = torch.FloatTensor(seg_data).permute(3, 0, 1, 2)  # [C, H, W, D]\n",
    "        \n",
    "        # Get temporal information (weeks since baseline)\n",
    "        week_num = self._extract_week_number(week_dir.name)\n",
    "        \n",
    "        return {\n",
    "            'mri': mri_stack,          # [4, 240, 240, 155]\n",
    "            'seg': seg_tensor,         # [3, 240, 240, 155]\n",
    "            'week': week_num,          # int\n",
    "            'patient_id': patient_dir.name,\n",
    "            'week_dir': week_dir.name\n",
    "        }\n",
    "\n",
    "    def _extract_week_number(self, week_str):\n",
    "        \"\"\"Handle complex week formats like week-092 or week-000-1\"\"\"\n",
    "        parts = week_str.split('-')\n",
    "        # Get the first numeric part after 'week'\n",
    "        return int(''.join(filter(str.isdigit, parts[1])))\n",
    "\n",
    "    def get_patient_weeks(self, patient_id):\n",
    "        \"\"\"Get all available weeks for a specific patient\"\"\"\n",
    "        return [week for (p, week) in self.patient_weeks if p.name == patient_id]\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    dataset = LUMIEREDataset(\n",
    "        root_dir='C:/Users/Tushar/Documents/LUMIERE/Imaging',\n",
    "       )\n",
    "    \n",
    "\n",
    "    patient_067_weeks = dataset.get_patient_weeks('Patient-067')\n",
    "    print(f\"Patient 067 has scans at weeks: {[w.name for _, w in patient_067_weeks]}\")\n",
    "    \n",
    "    sample = dataset[0]\n",
    "    print(f\"MRI shape: {sample['mri'].shape}\")\n",
    "    print(f\"Segmentation shape: {sample['seg'].shape}\")\n",
    "    print(f\"Week number: {sample['week']}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "42d3d72d-6411-4239-aa40-0638c1a1462e",
   "metadata": {},
   "outputs": [],
   "source": [
    "class GliomaGrowthPredictor(nn.Module):\n",
    "    def __init__(self, input_channels=4, output_channels=3):\n",
    "        super().__init__()\n",
    "\n",
    "        self.encoder = nn.Sequential(\n",
    "            nn.Conv3d(input_channels, 32, kernel_size=3, padding=1),\n",
    "            nn.InstanceNorm3d(32),\n",
    "            nn.LeakyReLU(),\n",
    "            nn.MaxPool3d(2),\n",
    "            \n",
    "            nn.Conv3d(32, 64, kernel_size=3, padding=1),\n",
    "            nn.InstanceNorm3d(64),\n",
    "            nn.LeakyReLU(),\n",
    "            nn.MaxPool3d(2)\n",
    "        )\n",
    "\n",
    "        self.ode_func = nn.Sequential(\n",
    "            nn.Linear(64 + 1, 128), \n",
    "            nn.LeakyReLU(),\n",
    "            nn.Linear(128, 64)\n",
    "        )\n",
    "\n",
    "\n",
    "        self.decoder = nn.Sequential(\n",
    "            nn.ConvTranspose3d(64, 32, kernel_size=3, stride=2, padding=1, output_padding=1),\n",
    "            nn.InstanceNorm3d(32),\n",
    "            nn.LeakyReLU(),\n",
    "            \n",
    "            nn.ConvTranspose3d(32, 16, kernel_size=3, stride=2, padding=1, output_padding=1),\n",
    "            nn.InstanceNorm3d(16),\n",
    "            nn.LeakyReLU(),\n",
    "            \n",
    "            nn.Conv3d(16, output_channels, kernel_size=1),\n",
    "            nn.Softmax(dim=1)\n",
    "        )\n",
    "\n",
    "    def forward(self, x, t):\n",
    "        features = self.encoder(x)\n",
    "        \n",
    "        def odefunc(_, state):\n",
    "            time_vec = t.expand(state.size(0), 1)\n",
    "            return self.ode_func(torch.cat([state, time_vec], 1))\n",
    "        \n",
    "        final_state = torchdiffeq.odeint(\n",
    "            odefunc,\n",
    "            features.mean(dim=[2,3,4]),  # Global pooled features\n",
    "            torch.tensor([0.0, t.item()], device=x.device),\n",
    "            method='dopri5'\n",
    "        )[-1]\n",
    "\n",
    "        return self.decoder(final_state.unsqueeze(-1).unsqueeze(-1).unsqueeze(-1))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0ee7be91-2a99-421b-96bd-23253e65abe8",
   "metadata": {},
   "outputs": [],
   "source": [
    "def train_lumiere():\n",
    "    device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
    "    \n",
    "    dataset = LUMIEREDataset(\n",
    "        Path('C:/Users/Tushar/Documents/LUMIERE/Imaging/'),\n",
    "        norm_params={\n",
    "            'CT1': {'mean': 0.94, 'std': 0.17},\n",
    "            'T1': {'mean': 0.71, 'std': 0.21},\n",
    "            'T2': {'mean': 0.70, 'std': 0.26},\n",
    "            'FLAIR': {'mean': 0.60, 'std': 0.21}\n",
    "        }\n",
    "    )\n",
    "    \n",
    "    model = GliomaGrowthPredictor().to(device)\n",
    "    optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-5)\n",
    "    loss_fn = nn.CrossEntropyLoss()\n",
    "\n",
    "\n",
    "    for epoch in range(100):\n",
    "        model.train()\n",
    "        total_loss = 0\n",
    "        \n",
    "        for patient in dataset:\n",
    "            for i in range(len(patient)-1):\n",
    "                current = patient[i]\n",
    "                next_scan = patient[i+1]\n",
    "                \n",
    "                # Prepare inputs [B,C,H,W,D]\n",
    "                inputs = current['mri'].unsqueeze(0).to(device)\n",
    "                delta_t = torch.FloatTensor([next_scan['delta_t'] - current['delta_t']]).to(device)\n",
    "                targets = next_scan['seg'].argmax(dim=0).unsqueeze(0).to(device)  # Convert to class indices\n",
    "                \n",
    "                optimizer.zero_grad()\n",
    "                outputs = model(inputs, delta_t)\n",
    "                \n",
    "                loss = loss_fn(outputs, targets)\n",
    "                loss.backward()\n",
    "                optimizer.step()\n",
    "                total_loss += loss.item()\n",
    "\n",
    "        if epoch % 10 == 0:\n",
    "            print(f'Epoch {epoch+1}/100 | Loss: {total_loss/len(dataset):.4f}')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ede7a7c1-4f08-41bf-a441-d6c28988eca9",
   "metadata": {},
   "outputs": [],
   "source": [
    "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
    "manual_mri = ManualMRI()\n",
    "dataset = TumorDataset(manual_mri, center_slice=5)\n",
    "dataloader = torch.utils.data.DataLoader(dataset, batch_size=2, shuffle=True)\n",
    "\n",
    "model = TumorODE().to(device)\n",
    "optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)\n",
    "loss_fn = nn.MSELoss()\n",
    "ssim = StructuralSimilarityIndexMeasure(data_range=1.0).to(device)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8b8af867-3e7b-4bd6-91bd-5b2d432077a0",
   "metadata": {},
   "outputs": [],
   "source": [
    "def plot_prediction(input_slices, prediction, target):\n",
    "    plt.figure(figsize=(15,5))\n",
    "    \n",
    "    plt.subplot(131)\n",
    "    plt.imshow(input_slices[0,0].cpu(), cmap='gray')\n",
    "    plt.title(\"Slice -1\")\n",
    "    \n",
    "    plt.subplot(132)\n",
    "    plt.imshow(input_slices[0,1].cpu(), cmap='gray')\n",
    "    plt.title(\"Center Slice (Input)\")\n",
    "    \n",
    "    plt.subplot(133)\n",
    "    plt.imshow(prediction[0,0].cpu().detach(), cmap='gray')\n",
    "    plt.title(\"Predicted Next Week\")\n",
    "    \n",
    "    plt.figure()\n",
    "    plt.imshow(target[0,0].cpu(), cmap='gray')\n",
    "    plt.title(\"Ground Truth\")\n",
    "    plt.show()\n",
    "\n",
    "for epoch in range(100):\n",
    "    model.train()\n",
    "    total_loss = 0\n",
    "    \n",
    "    for inputs, delta_t, targets, segs in dataloader:\n",
    "        inputs = inputs.to(device)\n",
    "        delta_t = delta_t.to(device)\n",
    "        targets = targets.to(device)\n",
    "        \n",
    "        optimizer.zero_grad()\n",
    "        preds = model(inputs, delta_t)\n",
    "        \n",
    "        loss = loss_fn(preds, targets)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        \n",
    "        total_loss += loss.item()\n",
    "    \n",
    "\n",
    "    model.eval()\n",
    "    with torch.no_grad():\n",
    "        val_input, val_t, val_target, _ = next(iter(dataloader))\n",
    "        val_pred = model(val_input.to(device), val_t.to(device))\n",
    "        val_ssim = ssim(val_pred, val_target.to(device))\n",
    "    \n",
    "    if epoch % 10 == 0:\n",
    "        print(f\"Epoch {epoch+1}/100\")\n",
    "        print(f\"Loss: {total_loss/len(dataloader):.4f}\")\n",
    "        print(f\"SSIM: {val_ssim:.4f}\")\n",
    "        plot_prediction(val_input, val_pred, val_target)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
